#!/bin/bash

source script/lib/diff-lib.sh

SOURCE_DIR="miniguava-collect/src/main/java/net/ypresto/miniguava/collect"
GUAVA_DIR="$GUAVA_ROOT_DIR/guava/src/com/google/common/collect"
GUAVA_BASE_DIR="$GUAVA_ROOT_DIR/guava/src/com/google/common/base"

find "$SOURCE_DIR" -type f -name '*.java' \
  | grep -vE '.*/Equivalence\.java$|.*/internal/.*|/Internal.*\.java$' \
  | while read full_path; do
  rel_path="${full_path#$SOURCE_DIR/}"
  show_diff "$GUAVA_DIR" "$SOURCE_DIR" "$rel_path" "$@" || exit 1
done || die

show_diff "$GUAVA_BASE_DIR" "$SOURCE_DIR" "Equivalence.java" "$@" || die
show_diff_fullpath "$GUAVA_BASE_DIR/Predicates.java" "$SOURCE_DIR/InternalPredicates.java" "$@" || die
show_diff "$GUAVA_DIR" "$SOURCE_DIR/internal" "AbstractIndexedListIterator.java" "$@" || die
show_diff "$GUAVA_DIR" "$SOURCE_DIR/internal" "AbstractMapEntry.java" "$@" || die
