#!/bin/bash

source script/lib/diff-lib.sh

SOURCE_DIR="miniguava-base/src/test/java/net/ypresto/miniguava"
GUAVA_DIR="$GUAVA_ROOT_DIR/guava-tests/test/com/google/common"

find "$SOURCE_DIR" -type f -name '*.java' \
  | while read full_path; do
  rel_path="${full_path#$SOURCE_DIR/}"
  show_diff "$GUAVA_DIR" "$SOURCE_DIR" "$rel_path" "$@" || exit 1
done || die
