#!/bin/bash

source script/lib/diff-lib.sh

SOURCE_DIR="miniguava-compare/src/test/java/net/ypresto/miniguava/compare"
GUAVA_DIR="$GUAVA_ROOT_DIR/guava-tests/test/com/google/common/collect"

find "$SOURCE_DIR" -type f -name '*.java' \
  | grep -vE '/PrimitiveComparisonTest.java$' \
  | while read full_path; do
  rel_path="${full_path#$SOURCE_DIR/}"
  show_diff "$GUAVA_DIR" "$SOURCE_DIR" "$rel_path" "$@" || exit 1
done || die
