#!/bin/bash

source script/lib/diff-lib.sh

SOURCE_DIR="miniguava-collect-immutables/src/test/java/net/ypresto/miniguava/collect/immutables"
GUAVA_DIR="$GUAVA_ROOT_DIR/guava-tests/test/com/google/common/collect"
GUAVA_TESTLIB_DIR="$GUAVA_ROOT_DIR/guava-testlib/src/com/google/common/collect/testing"

find "$SOURCE_DIR" -type f -name '*.java' \
  | grep -vE '/ListGenerators.java$|/ImmutablesTest.java$|/Internal.*\.java$' \
  | while read full_path; do
  rel_path="${full_path#$SOURCE_DIR/}"
  show_diff "$GUAVA_DIR" "$SOURCE_DIR" "$rel_path" "$@" || exit 1
done || die

show_diff "$GUAVA_TESTLIB_DIR/google" "$SOURCE_DIR" "ListGenerators.java" "$@" || die
