#!/bin/bash

source script/lib/diff-lib.sh

SOURCE_DIR="miniguava-collect-immutables/src/main/java/net/ypresto/miniguava/collect/immutables"
GUAVA_DIR="$GUAVA_ROOT_DIR/guava/src/com/google/common/collect"

find "$SOURCE_DIR" -type f -name '*.java' \
  | grep -vE '/Immutables.java$|/Internal.*\.java$' \
  | while read full_path; do
  rel_path="${full_path#$SOURCE_DIR/}"
  show_diff "$GUAVA_DIR" "$SOURCE_DIR" "$rel_path" "$@" || exit 1
done || die

show_diff_fullpath "$GUAVA_DIR/Iterators.java" "$SOURCE_DIR/InternalIterators.java" "$@" || die
show_diff_fullpath "$GUAVA_DIR/Lists.java" "$SOURCE_DIR/InternalLists.java" "$@" || die
